name: Terraform to C4 Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-diagram-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Terraform Show JSON
        working-directory: terraform
        run: terraform show -json tfplan > ../terraform_state.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script to Process Terraform JSON
        run: python process_terraform.py